package minesweeper;

import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import sun.io.ByteToCharUnicodeLittleUnmarked;

public class BoardGUI extends javax.swing.JFrame {

    public int height = 15, width = 15, numMines = 30;
    Board board = new Board(height, width, numMines);
    int i = 0;
    static JPanel panel;
    final JButton[][] buttons = new JButton[height][width];

    public BoardGUI() {

        setDefaultCloseOperation(EXIT_ON_CLOSE);

        panel = new JPanel(new GridLayout(height, width));

        for (int x = 0; x < width; x++) {
            for (int y = 0; y < height; y++) {
                buttons[x][y] = new JButton(" ");
                buttons[x][y].setSize(100, 100);
                buttons[x][y].setActionCommand(String.valueOf(x) + "_" + String.valueOf(y));
                buttons[x][y].setName(String.valueOf(x) + "_" + String.valueOf(y));

                buttons[x][y].addActionListener(new ActionListener() {

                    public void actionPerformed(ActionEvent e) {
                        String choice = e.getActionCommand();
                        String[] coords = choice.split("_");
                        int t_x = Integer.parseInt(coords[0]);
                        int t_y = Integer.parseInt(coords[1]);
                        board.click(t_x, t_y);

                        if (board.hasLost) {
                            JOptionPane.showMessageDialog(null, "Sorry, you lose");
                            System.exit(0);
                        }
                        if (board.hasWon) {
                            JOptionPane.showMessageDialog(null, "You win!!");
                            System.exit(0);
                        }
                        clickBtn();
                        drawBtns();
                    }
                });
                buttons[x][y].addMouseListener(new RightClicker());
                panel.add(buttons[x][y]);
            }
        }

    }

    // this I got from a web forum
    private class RightClicker extends MouseAdapter {

        public void mousePressed(MouseEvent e) {
            if (e.isMetaDown()) {
                JButton src = (JButton) e.getSource();
                String choice = src.getName();
                String[] coords = choice.split("_");
                int t_x = Integer.parseInt(coords[0]);
                int t_y = Integer.parseInt(coords[1]);
                board.rightClick(t_x, t_y);

                clickBtn();
                drawBtns();
            }
        }
    }

    public void drawBtns() {
        for (int x = 0; x < width; x++) {
            for (int y = 0; y < height; y++) {
                if (board.board[x][y] == -1 || board.board[x][y] == -2) {
                    buttons[x][y].setBackground(Color.GRAY);
                    buttons[x][y].setText(" ");
                } else if (board.board[x][y] == -3 || board.board[x][y] == -4) {
                    buttons[x][y].setBackground(Color.LIGHT_GRAY);
                    buttons[x][y].setText("F");
                } else {
                    buttons[x][y].setBackground(Color.WHITE);
                    buttons[x][y].setText(String.valueOf(board.board[x][y]));
                }
            }
        }
    }

    public void clickBtn() {
        // this is just to help keep track and for debugging
        board.print();
        System.out.println();
    }

    /**
     * Creates new form BoardGUI
     */
    public static void drawBoard(BoardGUI frame) {
        frame.add(panel);
        frame.pack();
        frame.setSize(frame.width * 50, frame.height * 50);
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        BoardGUI frame = new BoardGUI();
        drawBoard(frame);


        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BoardGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
